
on: [push]

name: tests

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/cache@master
        id: yarn-cache
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-lerna-${{ hashFiles('**/package.json', '**/yarn.lock') }}
      - run: yarn install --network-concurrency 1
        if: ${{ steps.yarn-cache.outputs.cache-hit != 'true' }}

  test:
    name: Test contracts
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/cache@master
        id: yarn-cache
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-lerna-${{ hashFiles('**/package.json', '**/yarn.lock') }}
      - run: yarn test

  # coverage:
  #   name: Coverage
  #   runs-on: ubuntu-latest
  #   needs: [install]
  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: 12
  #     - uses: actions/cache@master
  #       id: yarn-cache
  #       with:
  #         path: |
  #           node_modules
  #           */*/node_modules
  #         key: ${{ runner.os }}-lerna-${{ hashFiles('**/package.json', '**/yarn.lock') }}
  #     - run: yarn coverage || true
  #     - name: Coveralls
  #       uses: coverallsapp/github-action@master
  #       with:
  #         github-token: ${{ secrets.GITHUB_TOKEN }}

  # lint-ts:
  #   name: Typescript lint
  #   runs-on: ubuntu-latest
  #   needs: [install]
  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: 12
  #     - uses: actions/cache@master
  #       id: yarn-cache
  #       with:
  #         path: |
  #           node_modules
  #           */*/node_modules
  #         key: ${{ runner.os }}-lerna-${{ hashFiles('**/package.json', '**/yarn.lock') }}
  #     - run: yarn lint:ts

  # lint-sol:
  #   name: Solidity lint
  #   runs-on: ubuntu-latest
  #   needs: [install]
  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: 12
  #     - uses: actions/cache@master
  #       id: yarn-cache
  #       with:
  #         path: |
  #           node_modules
  #           */*/node_modules
  #         key: ${{ runner.os }}-lerna-${{ hashFiles('**/package.json', '**/yarn.lock') }}
  #     - run: yarn lint:sol
